// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"zotregistry.io/zot/ent/element"
	"zotregistry.io/zot/ent/predicate"
	"zotregistry.io/zot/ent/resource"
	"zotregistry.io/zot/ent/statement"
)

// ElementQuery is the builder for querying Element entities.
type ElementQuery struct {
	config
	ctx                 *QueryContext
	order               []element.OrderOption
	inters              []Interceptor
	predicates          []predicate.Element
	withStatements      *StatementQuery
	withResources       *ResourceQuery
	withLocations       *ResourceQuery
	withFKs             bool
	modifiers           []func(*sql.Selector)
	loadTotal           []func(context.Context, []*Element) error
	withNamedStatements map[string]*StatementQuery
	withNamedResources  map[string]*ResourceQuery
	withNamedLocations  map[string]*ResourceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ElementQuery builder.
func (eq *ElementQuery) Where(ps ...predicate.Element) *ElementQuery {
	eq.predicates = append(eq.predicates, ps...)
	return eq
}

// Limit the number of records to be returned by this query.
func (eq *ElementQuery) Limit(limit int) *ElementQuery {
	eq.ctx.Limit = &limit
	return eq
}

// Offset to start from.
func (eq *ElementQuery) Offset(offset int) *ElementQuery {
	eq.ctx.Offset = &offset
	return eq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (eq *ElementQuery) Unique(unique bool) *ElementQuery {
	eq.ctx.Unique = &unique
	return eq
}

// Order specifies how the records should be ordered.
func (eq *ElementQuery) Order(o ...element.OrderOption) *ElementQuery {
	eq.order = append(eq.order, o...)
	return eq
}

// QueryStatements chains the current query on the "statements" edge.
func (eq *ElementQuery) QueryStatements() *StatementQuery {
	query := (&StatementClient{config: eq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(element.Table, element.FieldID, selector),
			sqlgraph.To(statement.Table, statement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, element.StatementsTable, element.StatementsColumn),
		)
		fromU = sqlgraph.SetNeighbors(eq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryResources chains the current query on the "resources" edge.
func (eq *ElementQuery) QueryResources() *ResourceQuery {
	query := (&ResourceClient{config: eq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(element.Table, element.FieldID, selector),
			sqlgraph.To(resource.Table, resource.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, element.ResourcesTable, element.ResourcesColumn),
		)
		fromU = sqlgraph.SetNeighbors(eq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLocations chains the current query on the "locations" edge.
func (eq *ElementQuery) QueryLocations() *ResourceQuery {
	query := (&ResourceClient{config: eq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(element.Table, element.FieldID, selector),
			sqlgraph.To(resource.Table, resource.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, element.LocationsTable, element.LocationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(eq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Element entity from the query.
// Returns a *NotFoundError when no Element was found.
func (eq *ElementQuery) First(ctx context.Context) (*Element, error) {
	nodes, err := eq.Limit(1).All(setContextOp(ctx, eq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{element.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eq *ElementQuery) FirstX(ctx context.Context) *Element {
	node, err := eq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Element ID from the query.
// Returns a *NotFoundError when no Element ID was found.
func (eq *ElementQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eq.Limit(1).IDs(setContextOp(ctx, eq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{element.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eq *ElementQuery) FirstIDX(ctx context.Context) int {
	id, err := eq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Element entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Element entity is found.
// Returns a *NotFoundError when no Element entities are found.
func (eq *ElementQuery) Only(ctx context.Context) (*Element, error) {
	nodes, err := eq.Limit(2).All(setContextOp(ctx, eq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{element.Label}
	default:
		return nil, &NotSingularError{element.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eq *ElementQuery) OnlyX(ctx context.Context) *Element {
	node, err := eq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Element ID in the query.
// Returns a *NotSingularError when more than one Element ID is found.
// Returns a *NotFoundError when no entities are found.
func (eq *ElementQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eq.Limit(2).IDs(setContextOp(ctx, eq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{element.Label}
	default:
		err = &NotSingularError{element.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eq *ElementQuery) OnlyIDX(ctx context.Context) int {
	id, err := eq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Elements.
func (eq *ElementQuery) All(ctx context.Context) ([]*Element, error) {
	ctx = setContextOp(ctx, eq.ctx, "All")
	if err := eq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Element, *ElementQuery]()
	return withInterceptors[[]*Element](ctx, eq, qr, eq.inters)
}

// AllX is like All, but panics if an error occurs.
func (eq *ElementQuery) AllX(ctx context.Context) []*Element {
	nodes, err := eq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Element IDs.
func (eq *ElementQuery) IDs(ctx context.Context) (ids []int, err error) {
	if eq.ctx.Unique == nil && eq.path != nil {
		eq.Unique(true)
	}
	ctx = setContextOp(ctx, eq.ctx, "IDs")
	if err = eq.Select(element.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eq *ElementQuery) IDsX(ctx context.Context) []int {
	ids, err := eq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eq *ElementQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, eq.ctx, "Count")
	if err := eq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, eq, querierCount[*ElementQuery](), eq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (eq *ElementQuery) CountX(ctx context.Context) int {
	count, err := eq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eq *ElementQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, eq.ctx, "Exist")
	switch _, err := eq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (eq *ElementQuery) ExistX(ctx context.Context) bool {
	exist, err := eq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ElementQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eq *ElementQuery) Clone() *ElementQuery {
	if eq == nil {
		return nil
	}
	return &ElementQuery{
		config:         eq.config,
		ctx:            eq.ctx.Clone(),
		order:          append([]element.OrderOption{}, eq.order...),
		inters:         append([]Interceptor{}, eq.inters...),
		predicates:     append([]predicate.Element{}, eq.predicates...),
		withStatements: eq.withStatements.Clone(),
		withResources:  eq.withResources.Clone(),
		withLocations:  eq.withLocations.Clone(),
		// clone intermediate query.
		sql:  eq.sql.Clone(),
		path: eq.path,
	}
}

// WithStatements tells the query-builder to eager-load the nodes that are connected to
// the "statements" edge. The optional arguments are used to configure the query builder of the edge.
func (eq *ElementQuery) WithStatements(opts ...func(*StatementQuery)) *ElementQuery {
	query := (&StatementClient{config: eq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eq.withStatements = query
	return eq
}

// WithResources tells the query-builder to eager-load the nodes that are connected to
// the "resources" edge. The optional arguments are used to configure the query builder of the edge.
func (eq *ElementQuery) WithResources(opts ...func(*ResourceQuery)) *ElementQuery {
	query := (&ResourceClient{config: eq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eq.withResources = query
	return eq
}

// WithLocations tells the query-builder to eager-load the nodes that are connected to
// the "locations" edge. The optional arguments are used to configure the query builder of the edge.
func (eq *ElementQuery) WithLocations(opts ...func(*ResourceQuery)) *ElementQuery {
	query := (&ResourceClient{config: eq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eq.withLocations = query
	return eq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ResourceType string `json:"resourceType,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Element.Query().
//		GroupBy(element.FieldResourceType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (eq *ElementQuery) GroupBy(field string, fields ...string) *ElementGroupBy {
	eq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ElementGroupBy{build: eq}
	grbuild.flds = &eq.ctx.Fields
	grbuild.label = element.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ResourceType string `json:"resourceType,omitempty"`
//	}
//
//	client.Element.Query().
//		Select(element.FieldResourceType).
//		Scan(ctx, &v)
func (eq *ElementQuery) Select(fields ...string) *ElementSelect {
	eq.ctx.Fields = append(eq.ctx.Fields, fields...)
	sbuild := &ElementSelect{ElementQuery: eq}
	sbuild.label = element.Label
	sbuild.flds, sbuild.scan = &eq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ElementSelect configured with the given aggregations.
func (eq *ElementQuery) Aggregate(fns ...AggregateFunc) *ElementSelect {
	return eq.Select().Aggregate(fns...)
}

func (eq *ElementQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range eq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, eq); err != nil {
				return err
			}
		}
	}
	for _, f := range eq.ctx.Fields {
		if !element.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eq.path != nil {
		prev, err := eq.path(ctx)
		if err != nil {
			return err
		}
		eq.sql = prev
	}
	return nil
}

func (eq *ElementQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Element, error) {
	var (
		nodes       = []*Element{}
		withFKs     = eq.withFKs
		_spec       = eq.querySpec()
		loadedTypes = [3]bool{
			eq.withStatements != nil,
			eq.withResources != nil,
			eq.withLocations != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, element.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Element).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Element{config: eq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(eq.modifiers) > 0 {
		_spec.Modifiers = eq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, eq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := eq.withStatements; query != nil {
		if err := eq.loadStatements(ctx, query, nodes,
			func(n *Element) { n.Edges.Statements = []*Statement{} },
			func(n *Element, e *Statement) { n.Edges.Statements = append(n.Edges.Statements, e) }); err != nil {
			return nil, err
		}
	}
	if query := eq.withResources; query != nil {
		if err := eq.loadResources(ctx, query, nodes,
			func(n *Element) { n.Edges.Resources = []*Resource{} },
			func(n *Element, e *Resource) { n.Edges.Resources = append(n.Edges.Resources, e) }); err != nil {
			return nil, err
		}
	}
	if query := eq.withLocations; query != nil {
		if err := eq.loadLocations(ctx, query, nodes,
			func(n *Element) { n.Edges.Locations = []*Resource{} },
			func(n *Element, e *Resource) { n.Edges.Locations = append(n.Edges.Locations, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range eq.withNamedStatements {
		if err := eq.loadStatements(ctx, query, nodes,
			func(n *Element) { n.appendNamedStatements(name) },
			func(n *Element, e *Statement) { n.appendNamedStatements(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range eq.withNamedResources {
		if err := eq.loadResources(ctx, query, nodes,
			func(n *Element) { n.appendNamedResources(name) },
			func(n *Element, e *Resource) { n.appendNamedResources(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range eq.withNamedLocations {
		if err := eq.loadLocations(ctx, query, nodes,
			func(n *Element) { n.appendNamedLocations(name) },
			func(n *Element, e *Resource) { n.appendNamedLocations(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range eq.loadTotal {
		if err := eq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (eq *ElementQuery) loadStatements(ctx context.Context, query *StatementQuery, nodes []*Element, init func(*Element), assign func(*Element, *Statement)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Element)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Statement(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(element.StatementsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.element_statements
		if fk == nil {
			return fmt.Errorf(`foreign-key "element_statements" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "element_statements" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (eq *ElementQuery) loadResources(ctx context.Context, query *ResourceQuery, nodes []*Element, init func(*Element), assign func(*Element, *Resource)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Element)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Resource(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(element.ResourcesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.element_resources
		if fk == nil {
			return fmt.Errorf(`foreign-key "element_resources" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "element_resources" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (eq *ElementQuery) loadLocations(ctx context.Context, query *ResourceQuery, nodes []*Element, init func(*Element), assign func(*Element, *Resource)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Element)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Resource(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(element.LocationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.element_locations
		if fk == nil {
			return fmt.Errorf(`foreign-key "element_locations" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "element_locations" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (eq *ElementQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eq.querySpec()
	if len(eq.modifiers) > 0 {
		_spec.Modifiers = eq.modifiers
	}
	_spec.Node.Columns = eq.ctx.Fields
	if len(eq.ctx.Fields) > 0 {
		_spec.Unique = eq.ctx.Unique != nil && *eq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, eq.driver, _spec)
}

func (eq *ElementQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(element.Table, element.Columns, sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt))
	_spec.From = eq.sql
	if unique := eq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if eq.path != nil {
		_spec.Unique = true
	}
	if fields := eq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, element.FieldID)
		for i := range fields {
			if fields[i] != element.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := eq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (eq *ElementQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eq.driver.Dialect())
	t1 := builder.Table(element.Table)
	columns := eq.ctx.Fields
	if len(columns) == 0 {
		columns = element.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if eq.sql != nil {
		selector = eq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if eq.ctx.Unique != nil && *eq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range eq.predicates {
		p(selector)
	}
	for _, p := range eq.order {
		p(selector)
	}
	if offset := eq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedStatements tells the query-builder to eager-load the nodes that are connected to the "statements"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (eq *ElementQuery) WithNamedStatements(name string, opts ...func(*StatementQuery)) *ElementQuery {
	query := (&StatementClient{config: eq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if eq.withNamedStatements == nil {
		eq.withNamedStatements = make(map[string]*StatementQuery)
	}
	eq.withNamedStatements[name] = query
	return eq
}

// WithNamedResources tells the query-builder to eager-load the nodes that are connected to the "resources"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (eq *ElementQuery) WithNamedResources(name string, opts ...func(*ResourceQuery)) *ElementQuery {
	query := (&ResourceClient{config: eq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if eq.withNamedResources == nil {
		eq.withNamedResources = make(map[string]*ResourceQuery)
	}
	eq.withNamedResources[name] = query
	return eq
}

// WithNamedLocations tells the query-builder to eager-load the nodes that are connected to the "locations"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (eq *ElementQuery) WithNamedLocations(name string, opts ...func(*ResourceQuery)) *ElementQuery {
	query := (&ResourceClient{config: eq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if eq.withNamedLocations == nil {
		eq.withNamedLocations = make(map[string]*ResourceQuery)
	}
	eq.withNamedLocations[name] = query
	return eq
}

// ElementGroupBy is the group-by builder for Element entities.
type ElementGroupBy struct {
	selector
	build *ElementQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (egb *ElementGroupBy) Aggregate(fns ...AggregateFunc) *ElementGroupBy {
	egb.fns = append(egb.fns, fns...)
	return egb
}

// Scan applies the selector query and scans the result into the given value.
func (egb *ElementGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, egb.build.ctx, "GroupBy")
	if err := egb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ElementQuery, *ElementGroupBy](ctx, egb.build, egb, egb.build.inters, v)
}

func (egb *ElementGroupBy) sqlScan(ctx context.Context, root *ElementQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(egb.fns))
	for _, fn := range egb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*egb.flds)+len(egb.fns))
		for _, f := range *egb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*egb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := egb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ElementSelect is the builder for selecting fields of Element entities.
type ElementSelect struct {
	*ElementQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (es *ElementSelect) Aggregate(fns ...AggregateFunc) *ElementSelect {
	es.fns = append(es.fns, fns...)
	return es
}

// Scan applies the selector query and scans the result into the given value.
func (es *ElementSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, es.ctx, "Select")
	if err := es.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ElementQuery, *ElementSelect](ctx, es.ElementQuery, es, es.inters, v)
}

func (es *ElementSelect) sqlScan(ctx context.Context, root *ElementQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(es.fns))
	for _, fn := range es.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*es.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := es.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
