// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"zotregistry.io/zot/ent/element"
	"zotregistry.io/zot/ent/predicate"
	"zotregistry.io/zot/ent/statement"
)

// StatementUpdate is the builder for updating Statement entities.
type StatementUpdate struct {
	config
	hooks    []Hook
	mutation *StatementMutation
}

// Where appends a list predicates to the StatementUpdate builder.
func (su *StatementUpdate) Where(ps ...predicate.Statement) *StatementUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetMediaType sets the "mediaType" field.
func (su *StatementUpdate) SetMediaType(s string) *StatementUpdate {
	su.mutation.SetMediaType(s)
	return su
}

// AddObjectIDs adds the "objects" edge to the Element entity by IDs.
func (su *StatementUpdate) AddObjectIDs(ids ...int) *StatementUpdate {
	su.mutation.AddObjectIDs(ids...)
	return su
}

// AddObjects adds the "objects" edges to the Element entity.
func (su *StatementUpdate) AddObjects(e ...*Element) *StatementUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return su.AddObjectIDs(ids...)
}

// AddPredicateIDs adds the "predicates" edge to the Element entity by IDs.
func (su *StatementUpdate) AddPredicateIDs(ids ...int) *StatementUpdate {
	su.mutation.AddPredicateIDs(ids...)
	return su
}

// AddPredicates adds the "predicates" edges to the Element entity.
func (su *StatementUpdate) AddPredicates(e ...*Element) *StatementUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return su.AddPredicateIDs(ids...)
}

// AddSubjectIDs adds the "subjects" edge to the Element entity by IDs.
func (su *StatementUpdate) AddSubjectIDs(ids ...int) *StatementUpdate {
	su.mutation.AddSubjectIDs(ids...)
	return su
}

// AddSubjects adds the "subjects" edges to the Element entity.
func (su *StatementUpdate) AddSubjects(e ...*Element) *StatementUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return su.AddSubjectIDs(ids...)
}

// AddStatementIDs adds the "statements" edge to the Element entity by IDs.
func (su *StatementUpdate) AddStatementIDs(ids ...int) *StatementUpdate {
	su.mutation.AddStatementIDs(ids...)
	return su
}

// AddStatements adds the "statements" edges to the Element entity.
func (su *StatementUpdate) AddStatements(e ...*Element) *StatementUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return su.AddStatementIDs(ids...)
}

// Mutation returns the StatementMutation object of the builder.
func (su *StatementUpdate) Mutation() *StatementMutation {
	return su.mutation
}

// ClearObjects clears all "objects" edges to the Element entity.
func (su *StatementUpdate) ClearObjects() *StatementUpdate {
	su.mutation.ClearObjects()
	return su
}

// RemoveObjectIDs removes the "objects" edge to Element entities by IDs.
func (su *StatementUpdate) RemoveObjectIDs(ids ...int) *StatementUpdate {
	su.mutation.RemoveObjectIDs(ids...)
	return su
}

// RemoveObjects removes "objects" edges to Element entities.
func (su *StatementUpdate) RemoveObjects(e ...*Element) *StatementUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return su.RemoveObjectIDs(ids...)
}

// ClearPredicates clears all "predicates" edges to the Element entity.
func (su *StatementUpdate) ClearPredicates() *StatementUpdate {
	su.mutation.ClearPredicates()
	return su
}

// RemovePredicateIDs removes the "predicates" edge to Element entities by IDs.
func (su *StatementUpdate) RemovePredicateIDs(ids ...int) *StatementUpdate {
	su.mutation.RemovePredicateIDs(ids...)
	return su
}

// RemovePredicates removes "predicates" edges to Element entities.
func (su *StatementUpdate) RemovePredicates(e ...*Element) *StatementUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return su.RemovePredicateIDs(ids...)
}

// ClearSubjects clears all "subjects" edges to the Element entity.
func (su *StatementUpdate) ClearSubjects() *StatementUpdate {
	su.mutation.ClearSubjects()
	return su
}

// RemoveSubjectIDs removes the "subjects" edge to Element entities by IDs.
func (su *StatementUpdate) RemoveSubjectIDs(ids ...int) *StatementUpdate {
	su.mutation.RemoveSubjectIDs(ids...)
	return su
}

// RemoveSubjects removes "subjects" edges to Element entities.
func (su *StatementUpdate) RemoveSubjects(e ...*Element) *StatementUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return su.RemoveSubjectIDs(ids...)
}

// ClearStatements clears all "statements" edges to the Element entity.
func (su *StatementUpdate) ClearStatements() *StatementUpdate {
	su.mutation.ClearStatements()
	return su
}

// RemoveStatementIDs removes the "statements" edge to Element entities by IDs.
func (su *StatementUpdate) RemoveStatementIDs(ids ...int) *StatementUpdate {
	su.mutation.RemoveStatementIDs(ids...)
	return su
}

// RemoveStatements removes "statements" edges to Element entities.
func (su *StatementUpdate) RemoveStatements(e ...*Element) *StatementUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return su.RemoveStatementIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *StatementUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *StatementUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StatementUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StatementUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *StatementUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(statement.Table, statement.Columns, sqlgraph.NewFieldSpec(statement.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.MediaType(); ok {
		_spec.SetField(statement.FieldMediaType, field.TypeString, value)
	}
	if su.mutation.ObjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.ObjectsTable,
			Columns: []string{statement.ObjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedObjectsIDs(); len(nodes) > 0 && !su.mutation.ObjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.ObjectsTable,
			Columns: []string{statement.ObjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ObjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.ObjectsTable,
			Columns: []string{statement.ObjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.PredicatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.PredicatesTable,
			Columns: []string{statement.PredicatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedPredicatesIDs(); len(nodes) > 0 && !su.mutation.PredicatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.PredicatesTable,
			Columns: []string{statement.PredicatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.PredicatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.PredicatesTable,
			Columns: []string{statement.PredicatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.SubjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.SubjectsTable,
			Columns: []string{statement.SubjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedSubjectsIDs(); len(nodes) > 0 && !su.mutation.SubjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.SubjectsTable,
			Columns: []string{statement.SubjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.SubjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.SubjectsTable,
			Columns: []string{statement.SubjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.StatementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.StatementsTable,
			Columns: []string{statement.StatementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedStatementsIDs(); len(nodes) > 0 && !su.mutation.StatementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.StatementsTable,
			Columns: []string{statement.StatementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.StatementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.StatementsTable,
			Columns: []string{statement.StatementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// StatementUpdateOne is the builder for updating a single Statement entity.
type StatementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StatementMutation
}

// SetMediaType sets the "mediaType" field.
func (suo *StatementUpdateOne) SetMediaType(s string) *StatementUpdateOne {
	suo.mutation.SetMediaType(s)
	return suo
}

// AddObjectIDs adds the "objects" edge to the Element entity by IDs.
func (suo *StatementUpdateOne) AddObjectIDs(ids ...int) *StatementUpdateOne {
	suo.mutation.AddObjectIDs(ids...)
	return suo
}

// AddObjects adds the "objects" edges to the Element entity.
func (suo *StatementUpdateOne) AddObjects(e ...*Element) *StatementUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return suo.AddObjectIDs(ids...)
}

// AddPredicateIDs adds the "predicates" edge to the Element entity by IDs.
func (suo *StatementUpdateOne) AddPredicateIDs(ids ...int) *StatementUpdateOne {
	suo.mutation.AddPredicateIDs(ids...)
	return suo
}

// AddPredicates adds the "predicates" edges to the Element entity.
func (suo *StatementUpdateOne) AddPredicates(e ...*Element) *StatementUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return suo.AddPredicateIDs(ids...)
}

// AddSubjectIDs adds the "subjects" edge to the Element entity by IDs.
func (suo *StatementUpdateOne) AddSubjectIDs(ids ...int) *StatementUpdateOne {
	suo.mutation.AddSubjectIDs(ids...)
	return suo
}

// AddSubjects adds the "subjects" edges to the Element entity.
func (suo *StatementUpdateOne) AddSubjects(e ...*Element) *StatementUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return suo.AddSubjectIDs(ids...)
}

// AddStatementIDs adds the "statements" edge to the Element entity by IDs.
func (suo *StatementUpdateOne) AddStatementIDs(ids ...int) *StatementUpdateOne {
	suo.mutation.AddStatementIDs(ids...)
	return suo
}

// AddStatements adds the "statements" edges to the Element entity.
func (suo *StatementUpdateOne) AddStatements(e ...*Element) *StatementUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return suo.AddStatementIDs(ids...)
}

// Mutation returns the StatementMutation object of the builder.
func (suo *StatementUpdateOne) Mutation() *StatementMutation {
	return suo.mutation
}

// ClearObjects clears all "objects" edges to the Element entity.
func (suo *StatementUpdateOne) ClearObjects() *StatementUpdateOne {
	suo.mutation.ClearObjects()
	return suo
}

// RemoveObjectIDs removes the "objects" edge to Element entities by IDs.
func (suo *StatementUpdateOne) RemoveObjectIDs(ids ...int) *StatementUpdateOne {
	suo.mutation.RemoveObjectIDs(ids...)
	return suo
}

// RemoveObjects removes "objects" edges to Element entities.
func (suo *StatementUpdateOne) RemoveObjects(e ...*Element) *StatementUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return suo.RemoveObjectIDs(ids...)
}

// ClearPredicates clears all "predicates" edges to the Element entity.
func (suo *StatementUpdateOne) ClearPredicates() *StatementUpdateOne {
	suo.mutation.ClearPredicates()
	return suo
}

// RemovePredicateIDs removes the "predicates" edge to Element entities by IDs.
func (suo *StatementUpdateOne) RemovePredicateIDs(ids ...int) *StatementUpdateOne {
	suo.mutation.RemovePredicateIDs(ids...)
	return suo
}

// RemovePredicates removes "predicates" edges to Element entities.
func (suo *StatementUpdateOne) RemovePredicates(e ...*Element) *StatementUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return suo.RemovePredicateIDs(ids...)
}

// ClearSubjects clears all "subjects" edges to the Element entity.
func (suo *StatementUpdateOne) ClearSubjects() *StatementUpdateOne {
	suo.mutation.ClearSubjects()
	return suo
}

// RemoveSubjectIDs removes the "subjects" edge to Element entities by IDs.
func (suo *StatementUpdateOne) RemoveSubjectIDs(ids ...int) *StatementUpdateOne {
	suo.mutation.RemoveSubjectIDs(ids...)
	return suo
}

// RemoveSubjects removes "subjects" edges to Element entities.
func (suo *StatementUpdateOne) RemoveSubjects(e ...*Element) *StatementUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return suo.RemoveSubjectIDs(ids...)
}

// ClearStatements clears all "statements" edges to the Element entity.
func (suo *StatementUpdateOne) ClearStatements() *StatementUpdateOne {
	suo.mutation.ClearStatements()
	return suo
}

// RemoveStatementIDs removes the "statements" edge to Element entities by IDs.
func (suo *StatementUpdateOne) RemoveStatementIDs(ids ...int) *StatementUpdateOne {
	suo.mutation.RemoveStatementIDs(ids...)
	return suo
}

// RemoveStatements removes "statements" edges to Element entities.
func (suo *StatementUpdateOne) RemoveStatements(e ...*Element) *StatementUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return suo.RemoveStatementIDs(ids...)
}

// Where appends a list predicates to the StatementUpdate builder.
func (suo *StatementUpdateOne) Where(ps ...predicate.Statement) *StatementUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *StatementUpdateOne) Select(field string, fields ...string) *StatementUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Statement entity.
func (suo *StatementUpdateOne) Save(ctx context.Context) (*Statement, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StatementUpdateOne) SaveX(ctx context.Context) *Statement {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *StatementUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StatementUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *StatementUpdateOne) sqlSave(ctx context.Context) (_node *Statement, err error) {
	_spec := sqlgraph.NewUpdateSpec(statement.Table, statement.Columns, sqlgraph.NewFieldSpec(statement.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Statement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, statement.FieldID)
		for _, f := range fields {
			if !statement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != statement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.MediaType(); ok {
		_spec.SetField(statement.FieldMediaType, field.TypeString, value)
	}
	if suo.mutation.ObjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.ObjectsTable,
			Columns: []string{statement.ObjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedObjectsIDs(); len(nodes) > 0 && !suo.mutation.ObjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.ObjectsTable,
			Columns: []string{statement.ObjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ObjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.ObjectsTable,
			Columns: []string{statement.ObjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.PredicatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.PredicatesTable,
			Columns: []string{statement.PredicatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedPredicatesIDs(); len(nodes) > 0 && !suo.mutation.PredicatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.PredicatesTable,
			Columns: []string{statement.PredicatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.PredicatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.PredicatesTable,
			Columns: []string{statement.PredicatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.SubjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.SubjectsTable,
			Columns: []string{statement.SubjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedSubjectsIDs(); len(nodes) > 0 && !suo.mutation.SubjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.SubjectsTable,
			Columns: []string{statement.SubjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.SubjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.SubjectsTable,
			Columns: []string{statement.SubjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.StatementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.StatementsTable,
			Columns: []string{statement.StatementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedStatementsIDs(); len(nodes) > 0 && !suo.mutation.StatementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.StatementsTable,
			Columns: []string{statement.StatementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.StatementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statement.StatementsTable,
			Columns: []string{statement.StatementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(element.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Statement{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
