// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"zotregistry.io/zot/ent/statement"
)

// Statement is the model entity for the Statement schema.
type Statement struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// MediaType holds the value of the "mediaType" field.
	MediaType string `json:"mediaType,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StatementQuery when eager-loading is set.
	Edges              StatementEdges `json:"edges"`
	element_statements *int
	selectValues       sql.SelectValues
}

// StatementEdges holds the relations/edges for other nodes in the graph.
type StatementEdges struct {
	// Objects holds the value of the objects edge.
	Objects []*Element `json:"objects,omitempty"`
	// Predicates holds the value of the predicates edge.
	Predicates []*Element `json:"predicates,omitempty"`
	// Subjects holds the value of the subjects edge.
	Subjects []*Element `json:"subjects,omitempty"`
	// Statements holds the value of the statements edge.
	Statements []*Element `json:"statements,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
	// totalCount holds the count of the edges above.
	totalCount [4]map[string]int

	namedObjects    map[string][]*Element
	namedPredicates map[string][]*Element
	namedSubjects   map[string][]*Element
	namedStatements map[string][]*Element
}

// ObjectsOrErr returns the Objects value or an error if the edge
// was not loaded in eager-loading.
func (e StatementEdges) ObjectsOrErr() ([]*Element, error) {
	if e.loadedTypes[0] {
		return e.Objects, nil
	}
	return nil, &NotLoadedError{edge: "objects"}
}

// PredicatesOrErr returns the Predicates value or an error if the edge
// was not loaded in eager-loading.
func (e StatementEdges) PredicatesOrErr() ([]*Element, error) {
	if e.loadedTypes[1] {
		return e.Predicates, nil
	}
	return nil, &NotLoadedError{edge: "predicates"}
}

// SubjectsOrErr returns the Subjects value or an error if the edge
// was not loaded in eager-loading.
func (e StatementEdges) SubjectsOrErr() ([]*Element, error) {
	if e.loadedTypes[2] {
		return e.Subjects, nil
	}
	return nil, &NotLoadedError{edge: "subjects"}
}

// StatementsOrErr returns the Statements value or an error if the edge
// was not loaded in eager-loading.
func (e StatementEdges) StatementsOrErr() ([]*Element, error) {
	if e.loadedTypes[3] {
		return e.Statements, nil
	}
	return nil, &NotLoadedError{edge: "statements"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Statement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case statement.FieldID:
			values[i] = new(sql.NullInt64)
		case statement.FieldMediaType:
			values[i] = new(sql.NullString)
		case statement.ForeignKeys[0]: // element_statements
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Statement fields.
func (s *Statement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case statement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case statement.FieldMediaType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mediaType", values[i])
			} else if value.Valid {
				s.MediaType = value.String
			}
		case statement.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field element_statements", value)
			} else if value.Valid {
				s.element_statements = new(int)
				*s.element_statements = int(value.Int64)
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Statement.
// This includes values selected through modifiers, order, etc.
func (s *Statement) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QueryObjects queries the "objects" edge of the Statement entity.
func (s *Statement) QueryObjects() *ElementQuery {
	return NewStatementClient(s.config).QueryObjects(s)
}

// QueryPredicates queries the "predicates" edge of the Statement entity.
func (s *Statement) QueryPredicates() *ElementQuery {
	return NewStatementClient(s.config).QueryPredicates(s)
}

// QuerySubjects queries the "subjects" edge of the Statement entity.
func (s *Statement) QuerySubjects() *ElementQuery {
	return NewStatementClient(s.config).QuerySubjects(s)
}

// QueryStatements queries the "statements" edge of the Statement entity.
func (s *Statement) QueryStatements() *ElementQuery {
	return NewStatementClient(s.config).QueryStatements(s)
}

// Update returns a builder for updating this Statement.
// Note that you need to call Statement.Unwrap() before calling this method if this Statement
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Statement) Update() *StatementUpdateOne {
	return NewStatementClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Statement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Statement) Unwrap() *Statement {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Statement is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Statement) String() string {
	var builder strings.Builder
	builder.WriteString("Statement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("mediaType=")
	builder.WriteString(s.MediaType)
	builder.WriteByte(')')
	return builder.String()
}

// NamedObjects returns the Objects named value or an error if the edge was not
// loaded in eager-loading with this name.
func (s *Statement) NamedObjects(name string) ([]*Element, error) {
	if s.Edges.namedObjects == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := s.Edges.namedObjects[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (s *Statement) appendNamedObjects(name string, edges ...*Element) {
	if s.Edges.namedObjects == nil {
		s.Edges.namedObjects = make(map[string][]*Element)
	}
	if len(edges) == 0 {
		s.Edges.namedObjects[name] = []*Element{}
	} else {
		s.Edges.namedObjects[name] = append(s.Edges.namedObjects[name], edges...)
	}
}

// NamedPredicates returns the Predicates named value or an error if the edge was not
// loaded in eager-loading with this name.
func (s *Statement) NamedPredicates(name string) ([]*Element, error) {
	if s.Edges.namedPredicates == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := s.Edges.namedPredicates[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (s *Statement) appendNamedPredicates(name string, edges ...*Element) {
	if s.Edges.namedPredicates == nil {
		s.Edges.namedPredicates = make(map[string][]*Element)
	}
	if len(edges) == 0 {
		s.Edges.namedPredicates[name] = []*Element{}
	} else {
		s.Edges.namedPredicates[name] = append(s.Edges.namedPredicates[name], edges...)
	}
}

// NamedSubjects returns the Subjects named value or an error if the edge was not
// loaded in eager-loading with this name.
func (s *Statement) NamedSubjects(name string) ([]*Element, error) {
	if s.Edges.namedSubjects == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := s.Edges.namedSubjects[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (s *Statement) appendNamedSubjects(name string, edges ...*Element) {
	if s.Edges.namedSubjects == nil {
		s.Edges.namedSubjects = make(map[string][]*Element)
	}
	if len(edges) == 0 {
		s.Edges.namedSubjects[name] = []*Element{}
	} else {
		s.Edges.namedSubjects[name] = append(s.Edges.namedSubjects[name], edges...)
	}
}

// NamedStatements returns the Statements named value or an error if the edge was not
// loaded in eager-loading with this name.
func (s *Statement) NamedStatements(name string) ([]*Element, error) {
	if s.Edges.namedStatements == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := s.Edges.namedStatements[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (s *Statement) appendNamedStatements(name string, edges ...*Element) {
	if s.Edges.namedStatements == nil {
		s.Edges.namedStatements = make(map[string][]*Element)
	}
	if len(edges) == 0 {
		s.Edges.namedStatements[name] = []*Element{}
	} else {
		s.Edges.namedStatements[name] = append(s.Edges.namedStatements[name], edges...)
	}
}

// Statements is a parsable slice of Statement.
type Statements []*Statement
