// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Element is the predicate function for element builders.
type Element func(*sql.Selector)

// Resource is the predicate function for resource builders.
type Resource func(*sql.Selector)

// Statement is the predicate function for statement builders.
type Statement func(*sql.Selector)
